title        = "Jennifer Thompson"
baseURL      = "https://jenthompson.me"
languageCode = "en-us"
theme        = "gohugo-theme-ananke"
ignoreFiles  = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
enableEmoji  = true

MetaDataFormat         = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu       = "main"
Paginate               = 5
googleAnalytics        = ""
enableRobotsTXT        = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  author = "Jennifer Thompson"
  dateFormat = "2006-01-02"
  description = "Hi. It's good to meet you."
  github = "https://github.com/jenniferthompson"
  facebook = ""
  twitter = "https://twitter.com/jent103"
  instagram = ""
  youtube = ""
  linkedin = "https://linkedin.com/jennifer-thompson-mph"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/hoh.jpg"
  recent_posts_number = 3
  body_classes = "avenir bg-near-white"

[permalinks]
  post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Resources"
    url = "/resources/index.html"
